name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run ESLint
        run: pnpm run lint

      - name: Run type-check
        run: pnpm run type-check

      - name: Run tests
        run: pnpm run test

      - name: Generate Prisma client
        run: pnpm prisma generate

      - name: Build
        run: pnpm run build
        env:
          NEXT_TELEMETRY_DISABLED: '1'
          DATABASE_URL: 'postgresql://user:password@localhost:5432/test'
          NEXTAUTH_SECRET: 'test-secret'
          NEXTAUTH_URL: 'http://localhost:3000'
